apiVersion: 1

groups:
  - name: system
    folder: system
    interval: 10s
    rules:
      - id: 1
        uid: disk-usage
        ruleGroup: system
        title: High disk space usage
        condition: condition
        noDataState: Alerting
        execErrState: Error
        for: 1m
        annotations:
          used-space: <code>{{ $values.display.Value }}%</code>
          instance: <code>{{ $labels.instance }}</code>
          mount-point: <code>{{ $labels.mountpoint }}</code>

        labels: { type: disk }
        data:
          - refId: data
            relativeTimeRange: { from: 300, to: 0 }
            datasourceUid: victoria-metrics
            model:
              editorMode: code
              expr: 100 - ((node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes)
              hide: false
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: true
              refId: data
          - refId: metric
            relativeTimeRange: { from: 300, to: 0 }
            datasourceUid: "-100"
            model:
              datasource:
                type: __expr__
                uid: "-100"
              expression: data
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
              reducer: max
              refId: Reduce
              type: reduce
          - refId: condition
            queryType: ''
            relativeTimeRange: { from: 300, to: 0 }
            datasourceUid: '-100'
            model:
              conditions:
              - evaluator:
                  params: [30, 0]
                  type: gt
                operator:
                  type: and
                query:
                  params: []
                reducer:
                  params: []
                  type: avg
                type: query
              datasource:
                name: Expression
                type: __expr__
                uid: __expr__
              expression: metric
              intervalMs: 1000
              maxDataPoints: 43200
              refId: condition
              type: threshold
          - refId: display
            datasourceUid: '-100'
            model:
              datasource:
                name: Expression
                type: __expr__
                uid: __expr__
              expression: round($metric * 100) / 100
              intervalMs: 1000
              maxDataPoints: 43200
              refId: display
              type: math
