[workspace]
members = ["censy", "veebot-telegram", "xtask"]

[profile.dev]
debug = 0

[workspace.package]
version = "0.4.1"

authors = ["Veetaha <veetaha2@gmail.com>"]
license = "MIT OR Apache-2.0"
publish = false

[workspace.dependencies]
anyhow              = "1.0"
assert_matches      = "1.5"
async-recursion     = "1.0"
async-trait         = "0.1"
base64              = "0.13"
bytes               = "1.1"
devx-cmd            = "0.5"
display-error-chain = "=0.1.1"
dotenv              = "0.15"
dptree              = "0.3"
duplicate           = "0.4"
easy-ext            = "1.0"
envy                = "0.4"
expect-test         = "1.4"
fs-err              = "2.7"
futures             = "0.3"
governor            = "0.5"
hmac                = "0.12"
itertools           = "0.10"
lazy-regex          = "2.3"
nanoid              = "0.4"
ogg-opus            = "0.1"
once_cell           = "1.14"
parking_lot         = "0.12"
rand                = "0.8"
serde               = "1.0"
serde_json          = "1.0"
thiserror           = "1.0"
tracing             = "0.1"
tracing-error       = "0.2"
tracing-futures     = "0.2"
tracing-log         = "0.1"
tracing-loki        = "0.2"
wav_io              = "0.1"
xshell              = "0.2"

# Deps with feature overrides
chrono             = { version = "0.4", features = ["clock", "std"], default-features = false }
clap               = { version = "4.0", features = ["derive"] }
reqwest            = { version = "0.11", features = ["rustls-tls", "json"], default-features = false }
serde_with         = { version = "2.0", features = ["json"] }
sqlx               = { version = "0.6", features = ["runtime-tokio-rustls", "postgres", "macros", "chrono", "offline"] }
timeago            = { version = "0.3", features = ["chrono"] }
tokio              = { version = "1.19", features = ["rt-multi-thread", "macros"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
url                = { version = "2.2", features = ["serde"] }
vergen             = { version = "7.2", features = ["build", "rustc", "git", "cargo"], default-features = false }

[workspace.dependencies.teloxide]
features = [
  "auto-send",
  "cache-me",
  "ctrlc_handler",
  "macros",
  "throttle",
  "trace-adaptor",
]
version = "0.10"

# Path deps
# censy = { path = "censy" }
