[workspace]
members = ["censy", "snowpity-tg", "xtask", "migration", "entities"]

[profile.dev]
debug = 0

[workspace.package]
version = "0.4.4"

authors = ["Veetaha <veetaha2@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[patch.crates-io]
# FIXME: remove this once https://github.com/teloxide/teloxide/pull/764 is merged and available
teloxide-core = { git = "https://github.com/Veetaha/teloxide", branch = "feat/add-missing-restricted-fields" }

[workspace.dependencies]
again                 = "0.1"
anyhow                = "1.0"
assert_matches        = "1.5"
async-recursion       = "1.0"
async-trait           = "0.1"
base64                = "0.13"
bytes                 = "1.1"
derive_more           = "0.99"
devx-cmd              = "0.5"
display-error-chain   = "=0.1.1"
dotenv                = "0.15"
dptree                = "0.3"
duplicate             = "0.4"
easy-ext              = "1.0"
envy                  = "0.4"
expect-test           = "1.4"
fs-err                = "2.7"
futures               = "0.3"
governor              = "0.5"
humansize             = "2.1"
itertools             = "0.10"
lazy-regex            = "2.3"
nanoid                = "0.4"
ogg-opus              = "0.1"
once_cell             = "1.14"
parking_lot           = "0.12"
prometheus            = "0.13"
rand                  = "0.8"
reqwest-middleware    = "0.2"
reqwest-retry         = "0.2"
serde_json            = "1.0"
serde_yaml            = "0.9"
sysinfo               = "0.26"
task-local-extensions = "0.1"
tempfile              = "3.3"
thiserror             = "1.0"
tokio                 = "1.21"
tracing               = "0.1"
tracing-futures       = "0.2"
url                   = "2.2"
wav_io                = "0.1"

# Deps with feature overrides
chrono = { version = "0.4", features = ["clock", "std"], default-features = false }
clap   = { version = "4.0", features = ["derive"] }

reqwest            = { version = "0.11", features = ["rustls-tls"], default-features = false }
sea-orm            = { version = "0.10", features = ["runtime-tokio-rustls", "sqlx-postgres"] }
sea-orm-migration  = { version = "0.10", features = ["runtime-tokio-rustls", "sqlx-postgres"] }
serde              = { version = "1.0", features = ["derive"] }
serde_with         = { version = "2.0", features = ["json"] }
teloxide           = { version = "0.11", features = ["rustls"], default-features = false }
timeago            = { version = "0.3", features = ["chrono"] }
tracing-error      = { version = "0.2", default-features = false }
tracing-loki       = { version = "0.2", features = ["rustls", "compat-0-2-1"], default-features = false }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
vergen             = { version = "7.2", features = ["build", "rustc", "git", "cargo"], default-features = false }

# Path deps
# censy = { path = "censy" }
