services:
  telegram_bot:
    image: veetaha/veebot-telegram:${VEEBOT_TG_IMAGE_TAG-latest}
    env_file: .env
    user: "${CURRENT_UID:?'Please run as follows: CURRENT_UID=$$(id -u):$$(id -g) docker compose up'}"
    build: .
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432

    # networks: [ postgres ]
    # depends_on: [ postgres ]

  # postgres:
  #   image: postgres:14.4
  #   user: "${CURRENT_UID:?'Please run as follows: CURRENT_UID=$$(id -u):$$(id -g) docker compose up'}"
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER:-admin}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}

  #   volumes:
  #     - ${PGDATA:-./data/postgres}:/var/lib/postgresql/data
  #     - /etc/passwd:/etc/passwd:ro
  #     - /etc/group:/etc/group:ro

  #   networks: [ postgres ]

  # pgadmin:
  #   image: dpage/pgadmin4:6.11
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}

  #   volumes:
  #      - ./pgadmin4/servers.json:/pgadmin4/servers.json:ro

  #   # volumes:
  #     #  - ${PGADMIN_DATA:-./data/pgadmin}:/var/lib/pgadmin

  #   ports:
  #     - "${PGADMIN_PORT:-5000}:80"
  #   networks: [ postgres ]

networks:
  postgres:
