services:
  telegram-bot:
    image: veetaha/veebot-telegram:${tag-latest}
    env_file: .env
    user: ${current_uid:?"Please run as follows 'current_uid=$(id -u):$(id -g) docker-compose up'"}
    build: .
