# See documentation for this config file at https://github.com/crate-ci/typos/blob/master/docs/reference.md

[default.extend-identifiers]

[files]
extend-exclude = [
  # Exclude generated files that are checked in to source control
  "Cargo.lock",

  # This grafana dashboard was copy-pasted from the internet, better leave
  # it as is, event with typos in it
  "docker/grafana/provisioning/dashboards/node-exporter-full_rev29.json",
]
