apiVersion: 1

datasources:
- name: victoria-metrics
  uid: victoria-metrics
  type: prometheus
  access: proxy
  url: http://victoria-metrics:8428
  isDefault: true
  editable: false

- name: loki
  uid: loki
  type: loki
  access: proxy
  url: http://loki:3100
