[package]
name = "entities"

authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
version = { workspace = true }

[dependencies]
sea-orm = { workspace = true }
