{
 "title": "Snowity Telegram",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Database queries total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (sql, result) (increase(snowpity_tg_db_query_duration_seconds_count))",
     "legendFormat": "({{result}}) {{sql}}"
    }
   ]
  },
  {
   "title": "Database requests duration",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "increase(snowpity_tg_db_query_duration_seconds_bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Generic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Telegram processed updates",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by (kind) (\r\n    increase((snowpity_tg_tg_updates_total unless snowpity_tg_tg_updates_skipped_total)[8i])\r\n    or\r\n    increase(snowpity_tg_tg_updates_total - snowpity_tg_tg_updates_skipped_total)\r\n)",
     "legendFormat": "(processed) {{kind}}"
    },
    {
     "expr": "sum(increase(snowpity_tg_tg_updates_total[2m]))",
     "legendFormat": "All updates"
    },
    {
     "expr": "sum(\r\n    increase(\r\n        (\r\n            (snowpity_tg_tg_updates_total unless snowpity_tg_tg_updates_skipped_total) \r\n            or\r\n            (snowpity_tg_tg_updates_total - snowpity_tg_tg_updates_skipped_total)\r\n        )\r\n        [8i]\r\n    )\r\n)",
     "legendFormat": "(processed) All updates"
    }
   ]
  },
  {
   "title": "HTTP requests duration",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "increase(snowpity_tg_http_request_duration_seconds_bucket[4i])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Inline queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Database media cache hits rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(snowpity_tg_blob_cache_hits_total) / sum(snowpity_tg_blob_cache_requests_total)",
     "legendFormat": "all time"
    }
   ]
  },
  {
   "title": "Inline query duration",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "sum by (le) (increase(snowpity_tg_inline_query_duration_seconds_bucket[4i]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Queries in flight",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "avg_over_time(avg(snowpity_tg_blob_cache_requests_in_flight_total[4i]))",
     "legendFormat": "In flight"
    }
   ]
  },
  {
   "title": "Telegram media upload file sizes",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "sum by (le) (increase(snowpity_tg_blob_original_size_bytes_bucket[4i]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Inline queries flow",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (result) (increase(snowpity_tg_inline_query_duration_seconds_count[8i]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration of media upload to Telegram",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "sum by (le) (increase(snowpity_tg_blob_tg_upload_duration_seconds_bucket[4i]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Inline queries by users",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "sum by (user) (increase(snowpity_tg_inline_queries_total[8i]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration of media download",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "sum by (le) (increase(snowpity_tg_blob_download_duration_seconds_bucket[4i]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Chosen inline results by posting platform",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "sum by (posting_platform_origin) (increase(snowpity_tg_chosen_inline_results_total[8i]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache hits",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 71 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(running_sum(increase(snowpity_tg_blob_cache_hits_total)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache misses",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 71 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(running_sum(increase(snowpity_tg_blob_cache_requests_total - snowpity_tg_blob_cache_hits_total)))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Inline queries statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Queries processed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 76 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (result) (running_sum(increase(snowpity_tg_inline_query_duration_seconds_count)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries accepted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 76 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (result) (running_sum(increase(snowpity_tg_chosen_inline_results_total)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Media ingested",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (result) (running_sum(increase(snowpity_tg_blob_original_size_bytes_sum)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processing time distribution",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (le) (running_sum(increase(snowpity_tg_inline_query_duration_seconds_bucket{result=\"ok\"})))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries skipped",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 80 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (result) (running_sum(increase(snowpity_tg_inline_queries_skipped_total)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Media sizes distribution",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (running_sum(increase(snowpity_tg_blob_original_size_bytes_bucket)))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "Panics",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 95 },
   "targets": [
    {
     "expr": "{ source=\"snowpity-tg\" } | json | _target = \"panic\" | line_format \"{{.message}} ----- {{.location}}\""
    }
   ]
  },
  {
   "title": "Errors",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 103 },
   "targets": [
    {
     "expr": "{ source=\"snowpity-tg\", level=\"error\" } | json | line_format \"{{.message}}\""
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 111 },
   "targets": [
    {
     "expr": "{ source=\"snowpity-tg\", level=\"warn\" } | json | line_format \"{{.message}}\""
    }
   ]
  }
 ]
}