[package]
name = "veebot-telegram"
version = "0.1.0"
authors = ["Veetaha <veetaha2@gmail.com>"]
edition = "2018"
publish = false
autobins = true

[dependencies]
async-trait = "0.1"
bytes = "1.1"
backtrace = "0.3"
chrono = { version = "0.4", default-features = false, features = ["clock", "std", "serde"] }
dotenv = "0.15"
envy = "0.4"
futures = "0.3"
itertools = "0.10"
nanoid = "0.4"
once_cell = "1.5"
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls", "json"] }
serde = "1.0"
serde_json = "1.0"
# texture-synthesis = "0.8.0"
thiserror = "1.0"
timeago = "0.3"
tokio = { version = "1.19", features = ["rt-multi-thread", "macros"] }
tracing = "0.1"
tracing-futures = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-log = "0.1"
url = { version = "2.2", features = ["serde"] }
sqlx = { version = "0.5", features = ["runtime-tokio-rustls", "postgres", "macros", "time"] }

teloxide = { version = "0.9", features = ["macros", "auto-send", "ctrlc_handler", "auto-send", "throttle"] }
