[package]
name = "censy"

edition = "2021"

license = { workspace = true }
publish = { workspace = true }
version = { workspace = true }

[dependencies]
itertools = { workspace = true }
once_cell = { workspace = true }
thiserror = { workspace = true }
