[package]
name = "censy"

authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
version = { workspace = true }

[dependencies]
itertools = { workspace = true }
once_cell = { workspace = true }
thiserror = { workspace = true }
