{
 "title": "Node Exporter / USE Method / Node",
 "tags": [ "linux-node-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_time_seconds, cluster)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_exporter_build_info{job=\"integrations/node_exporter\", cluster=\"$cluster\"}, instance)"
    }
   },
   { "name": "loki_datasource", "label": "Loki Data Source", "query": "loki" },
   {
    "name": "unit",
    "label": "Systemd Unit",
    "query": "label_values({job=\"integrations/node_exporter\", instance=\"$instance\", cluster=\"$cluster\"}, unit)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "instance:node_cpu_utilisation:rate5m{job=\"integrations/node_exporter\", instance=\"$instance\", cluster=\"$cluster\"} != 0",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "CPU Saturation (Load1 per CPU)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "instance:node_load1_per_cpu:ratio{job=\"integrations/node_exporter\", instance=\"$instance\", cluster=\"$cluster\"} != 0",
     "legendFormat": "Saturation"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "instance:node_memory_utilisation:ratio{job=\"integrations/node_exporter\", instance=\"$instance\", cluster=\"$cluster\"} != 0",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "Memory Saturation (Major Page Faults)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "rds" }
   ],
   "targets": [
    {
     "expr": "instance:node_vmstat_pgmajfault:rate5m{job=\"integrations/node_exporter\", instance=\"$instance\", cluster=\"$cluster\"} != 0",
     "legendFormat": "Major page Faults"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network Utilisation (Bytes Receive/Transmit)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "instance:node_network_receive_bytes_excluding_lo:rate5m{job=\"integrations/node_exporter\", instance=\"$instance\", cluster=\"$cluster\"} != 0",
     "legendFormat": "Receive"
    },
    {
     "expr": "instance:node_network_transmit_bytes_excluding_lo:rate5m{job=\"integrations/node_exporter\", instance=\"$instance\", cluster=\"$cluster\"} != 0",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "Network Saturation (Drops Receive/Transmit)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "instance:node_network_receive_drop_excluding_lo:rate5m{job=\"integrations/node_exporter\", instance=\"$instance\", cluster=\"$cluster\"} != 0",
     "legendFormat": "Receive"
    },
    {
     "expr": "instance:node_network_transmit_drop_excluding_lo:rate5m{job=\"integrations/node_exporter\", instance=\"$instance\", cluster=\"$cluster\"} != 0",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk IO Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "instance_device:node_disk_io_time_seconds:rate5m{job=\"integrations/node_exporter\", instance=\"$instance\", cluster=\"$cluster\"} != 0",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk IO Saturation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "instance_device:node_disk_io_time_weighted_seconds:rate5m{job=\"integrations/node_exporter\", instance=\"$instance\", cluster=\"$cluster\"} != 0",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk Space Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sort_desc(1 -\n  (\n   max without (mountpoint, fstype) (node_filesystem_avail_bytes{job=\"integrations/node_exporter\", fstype!=\"\", instance=\"$instance\", cluster=\"$cluster\"})\n   /\n   max without (mountpoint, fstype) (node_filesystem_size_bytes{job=\"integrations/node_exporter\", fstype!=\"\", instance=\"$instance\", cluster=\"$cluster\"})\n  ) != 0\n)\n",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Errors in system logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "{level=~\"err|crit|alert|emerg\",unit=~\"$unit\", job=\"integrations/node_exporter\", instance=\"$instance\", cluster=\"$cluster\"}"
    },
    {
     "expr": "{filename=~\"/var/log/syslog*|/var/log/messages*\", job=\"integrations/node_exporter\", instance=\"$instance\", cluster=\"$cluster\"} |~\".+(?i)error(?-i).+\""
    }
   ]
  },
  {
   "title": "authlog",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "{unit=\"ssh.service\", job=\"integrations/node_exporter\", instance=\"$instance\", cluster=\"$cluster\"}"
    },
    {
     "expr": "{filename=~\"/var/log/auth.log|/var/log/secure\", job=\"integrations/node_exporter\", instance=\"$instance\", cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Kernel logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "{transport=\"kernel\", job=\"integrations/node_exporter\", instance=\"$instance\", cluster=\"$cluster\"}"
    },
    {
     "expr": "{filename=\"/var/log/kern.log\", job=\"integrations/node_exporter\", instance=\"$instance\", cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "All system logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "{transport!=\"\", job=\"integrations/node_exporter\", instance=\"$instance\", cluster=\"$cluster\"}"
    },
    {
     "expr": "{filename!=\"\", job=\"integrations/node_exporter\", instance=\"$instance\", cluster=\"$cluster\"}"
    }
   ]
  }
 ]
}