#cloud-config

# Installs docker and docker-compose on the server
# Based on instructions from https://docs.docker.com/engine/install/ubuntu/
# and several github gists from here and there

groups: [docker]

users:
  - name: admin
    lock_passwd: true
    shell: /bin/bash
    ssh_authorized_keys: ["${ssh_public_key}"]
    groups: docker
    sudo: ALL=(ALL) NOPASSWD:ALL

package_update: true
package_upgrade: true
package_reboot_if_required: true
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg

runcmd:
  - export GPG=/etc/apt/keyrings/docker.gpg
  - export URL=https://download.docker.com/linux/ubuntu
  - mkdir -p /etc/apt/keyrings
  - curl -fsSL $URL/gpg | gpg --dearmor -o $GPG
  - 'echo "deb [arch=$(dpkg --print-architecture) signed-by=$GPG] $URL $(lsb_release -cs) stable"
    | tee /etc/apt/sources.list.d/docker.list > /dev/null'
  - apt-get update -y
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
  - systemctl start docker
  - systemctl enable docker
